# Generated by Django 2.2.1 on 2019-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='image',
            field=models.CharField(default='google.pe', max_length=400),
            preserve_default=False,
        ),
    ]
